language: python
python: 2.7
install: "pip install Lektor"
script: "sh ./travis_test.sh"
before_deploy:
  - openssl aes-256-cbc -K $encrypted_1c9ebd4878cf_key -iv $encrypted_1c9ebd4878cf_iv -in deploy_keys.tar.enc -out deploy_keys.tar -d
  - tar xvf deploy_keys.tar
  - ls -l
deploy:
  provider: script
  script: "sh ./travis_deploy.sh"
